/**
 * The assistant's product knowledge: what Skope does and how to use it, fed
 * into every assistant request so answers reference real screens and real
 * behaviour instead of guesses.
 *
 * KEEP THIS CURRENT. When you change user-facing behaviour (a wizard step, a
 * page, a plan limit, an offer, an endpoint the customer touches), update the
 * matching section here in the same change. The assistant repeats this file to
 * customers; stale text here is a support bug. Dated facts (offers, prices)
 * carry their dates so drift is visible.
 */
export const PRODUCT_CONTEXT = `SKOPE PRODUCT GUIDE (for answering "how do I…" questions; navigation paths are real)

What Skope is: a DPDP consent management platform for Indian websites. One script tag adds a consent banner, blocks trackers until consent, records tamper-evident consent receipts, hosts the privacy notice and a preference centre, and manages data-principal rights requests.

DASHBOARD PAGES (left sidebar): Sites (home, one card per site with setup progress), Records (consent receipts), Requests (rights-request queue), Compliance (breach reporting, erasure queue, recipients register, and SDF tools), Assistant (this chat), Team (on plans with more than one seat), Billing.

SITE SETUP WIZARD, open a site from Sites; five steps, in order:
1. "Install Skope": copy the snippet <script src="…/skope.js" data-site="sk_live_…" defer></script> into the site's <head>. To block a tracker until consent, change its script tag to type="text/plain" with data-skope and data-skope-purpose="analytics" (or "marketing"); Skope releases it when that purpose is granted. Google Consent Mode v2 defaults to denied automatically. The step completes itself when Skope sees the tag load on any real page, this works on localhost too: just open a local page carrying the tag in a browser. If no load was ever seen, the "check" fetches the registered domain and looks for the tag, so an undeployed site will report "tag not found" until a page actually loads it. The script also exposes window.skope.getConsent() and window.skope.openPreferences().
2. "Customize your banner": layout (bottom bar, centre modal, corner card), accent colour, heading/description/button copy, languages. The first language is the default; the rest are auto-translated on save and reviewable in the preview. All 22 Eighth Schedule languages plus English are available on every plan. Optional language switcher and a persistent "privacy choices" button for easy withdrawal.
3. "Declare the data you collect" (DPDP §5, the notice must itemize personal data, not just cookies): add each item (name, email, PAN…) with a category, the purpose it serves, where it's collected, and an optional retention period. Quick-add presets cover common items; or upload a screenshot of any form and Skope suggests the fields it sees (the image is read once and discarded, never stored). Declared items appear in the privacy notice and under each purpose in the banner's manage view.
4. "Add your contact": legal entity name, grievance officer (name + email required, DPDP requires a working grievance contact), optional DPO, and the response window in days (default 30) which sets the due-date clock on rights requests.
5. "Publish your privacy notice": generate a draft from the site's real settings (purposes, trackers found, declared data items, contacts), edit it, publish. Published versions are immutable and checksummed; publishing a new version makes returning visitors re-consent. The public notice lives at /p/<siteKey>/privacy in every enabled language.

Finishing these five steps gets the site live ("your essentials are live"); it is the baseline, not the whole of DPDP. Below the wizard, a "Go further" section on the site page holds the settings that cover the rest of your duties, set the ones that apply: Data retention (inactivity window), Children's data (child mode), Who you share data with (recipients register), and Exemptions you rely on. Skope does not claim a site is fully "compliant", it gives you the tools and an audit trail.

PURPOSES: a fixed set today, "Strictly necessary" (always on, no consent needed), "Analytics", and "Marketing". Visitors choose per purpose in the banner's manage view.

PREFERENCE CENTRE (hosted, no code): /p/<siteKey>/preferences. Visitors verify by email OTP, then view and change consent, withdraw (one tap, as easy as granting, that's the law), or file a rights request.

CONSENT MECHANICS (DPDP §6): on the first banner, non-essential purposes (analytics, marketing) are never pre-ticked, granting needs a clear affirmative action. "Reject non-essential" sits beside "Accept all" as an equal choice, and saving the manage view with nothing ticked grants only essential. The banner's manage view also shows the DPO (or, if none, the grievance officer) as the contact for exercising rights (§6(3)). These invariants are locked by e2e/consent-mechanics.spec.ts.

DPB COMPLAINTS (DPDP §5(1)(iii)): every generated notice includes a concrete "Complaints to the Data Protection Board" section with the Board's channel (kept current in lib/policy/dpb-channel.ts).

RIGHTS REQUESTS (Requests page): five types, access, correction, erasure, nomination, grievance. Flow: visitor submits on the preference centre → confirms by email → lands in the queue as "new" with a due date from the site's response window → the team works it (in progress) → closes it (done/rejected) with a resolution note. Overdue requests are flagged. Requester contact details are stored encrypted. For an access request, "Generate data summary (§11) PDF" assembles the site's declared data, purposes, recipients, retention, and contacts into a deliverable summary; verify the requester's identity before sending it (Skope assembles the summary but does not run identity-document checks).

RECORDS & PROOF (Records page): every consent decision is a receipt in a per-site hash chain (each row cryptographically linked to the previous; the database refuses edits). Each receipt also pins the checksum of the exact published notice shown at consent time (DPDP §6(10)), so the precise notice is self-contained and independently verifiable. The page shows recent receipts; "Download CSV" exports the full history on any plan. "Download audit bundle" (Growth-level access) produces the regulator-ready ZIP: receipts per site (incl. notice_checksum), every published notice version, a fresh chain-verification report, requests CSV, the compliance records (breaches, erasure, recipients, cessation, parental consents, SDF, retrospective deliveries, nominations, exemptions), a SHA-256 manifest, and a PDF cover sheet. Anyone can independently anchor a site's chain head at /api/v1/ledger-head/<siteKey>.

COMPLIANCE (Compliance page): a hub for the DPDP duties beyond the everyday banner/records flow. Available on every plan, these are legal obligations, never paywalled.
- Breach reporting (DPDP §8(6)): record a personal-data breach (what happened, when detected, categories of data, estimated people affected, remediation). Skope generates draft notices to the Data Protection Board and to affected people from the incident plus your contact details, and you mark when each was sent, those timestamps and notice snapshots are kept for the record and included in the audit bundle. The exact Board form/channel is set by the Rules, so the drafts carry flagged gaps for counsel to confirm; Skope does not auto-submit to the Board, and it holds no list of your affected people's emails (you send the notices from your own systems).
- Erasure queue (DPDP §8(7)-(8), §12(3)): when someone withdraws consent, an erasure obligation opens automatically with a due date (your response window). A daily retention sweep also opens one for any person who's had no consent activity past your inactivity window (the §8(8) "purpose no longer served" period, set per site under "Data retention" on the site page, default 3 years, flagged for counsel). Skope does NOT delete your data, your data lives in your systems, so you erase it there and mark the obligation done, or mark it "not required" with a reason (e.g. a legal retention hold). The queue and its resolutions go into the audit bundle.

RECIPIENTS REGISTER (DPDP §5/§8(2)/§11(1)(b), "Recipients register" on the site page; org-wide view under Compliance → Recipients register): list everyone you share personal data with, processors (vendors acting for you) and other fiduciaries, with the purpose, the data shared, their country, and (for processors) the contract reference and status. This feeds the privacy notice's "Who we share your data with" and "International transfers" sections, and the access-request summary. The org-wide page flags processors without a signed contract (§8(2)) and any destination on a restricted-transfer list (§16; empty until the Government notifies one). Each recipient can carry an optional cease-webhook URL for processor-cease signalling.

PROCESSOR CEASE (DPDP §6(6)/§8(7)(b), under each item in the Erasure queue): when someone withdraws, Skope opens a cessation task for each recipient. A recipient with a cease-webhook can be signalled automatically ("Signal webhook"); others are handled manually ("Mark acknowledged" / "Done manually"). The trail records when cessation was effected and is included in the audit bundle.

SIGNIFICANT DATA FIDUCIARY (DPDP §10, Compliance → Significant Data Fiduciary): for the few businesses the Government formally notifies as SDFs. Turn on the designation to unlock the §10 duties: attest your DPO is India-based, store Data Protection Impact Assessments (a structured template), record your independent data auditor, and set an audit cadence. When a periodic audit falls due, Skope emails the billing contact a reminder (weekly until done) and you mark it complete to roll the next due date. This is gated by the SDF flag, not by plan. Don't designate unless you've been notified.

NOMINATIONS (DPDP §14, Compliance → Nominations): record who a person nominated to exercise their rights if they die or become incapacitated (nominee name + contact, encrypted at rest, with the relationship). Later you "Activate" the nomination (with proof) so the nominee can act for the principal, or "Revoke" it. Statuses and timestamps go into the audit bundle.

EXEMPTIONS & DUTIES (DPDP §15, §17, §9(4)): you can flag a grievance request as false/frivolous (§15) from the Requests page. On each site page you can record the §17 / §9(4) exemption grounds you rely on (free text, for your audit trail), whether an exemption actually applies is fact-specific, so confirm with counsel. Recorded exemptions and the consent-mechanics conformity statement are exported in the audit bundle.

RETROSPECTIVE NOTICE (DPDP §5(2), Compliance → Retrospective notice): if you collected personal data before the Act commenced, you must give those people the §5 notice as soon as practicable. The banner only re-prompts returning visitors, so this is a one-time broadcast: paste your existing contact emails, pick the site, and Skope emails each a link to that site's published privacy notice and logs per-recipient delivery (queued → sent/failed) for your burden-of-proof record. Emails are encrypted at rest; sending happens on the daily sweep. Publish the notice before sending.

CHILDREN'S DATA (DPDP §9, "Children's data" on the site page): if your service is used by under-18s, turn on child mode. The banner then asks "Are you 18 or older?" before consent. An adult continues normally. A child is held to essential-only, analytics and marketing trackers stay blocked no matter what the UI shows, and is asked for a parent/guardian's email; Skope emails the guardian a link to confirm verifiable parental consent (DPDP §9(1)). Confirming records a 'parental_grant' receipt in the ledger. Crucially, even after parental consent, Skope keeps tracking, behavioural monitoring, and targeted ads off for children (§9(3)), parental consent only covers the essential processing needed to run the service. The privacy notice's children section reflects whether child mode is on and any §9(4)/(5) exemption you record. The verifiable-consent mechanism (guardian email + declaration today) is interim and pluggable, confirm it with counsel; the Rules haven't prescribed one.

GEO MODES (per site): "India only" (default, banner shows only to visitors in India), "Global", or a custom country list.

TEAM (Team page): roles are owner, admin, viewer (viewers can't change anything). Invites are available on plans with more than one seat (Growth: 3 seats, Scale: 10).

BILLING & THE LAUNCH OFFER (Billing page), dated facts, verify against today's date:
- Launch offer: every org that signs up before 12 July 2026 gets 6 months of Growth-level access free, no card. Payments are paused for everyone until 12 August 2026, nothing can be purchased and nothing is owed before then.
- Plans (what pricing looks like after that): Free ₹0 (5,000 consents/mo, 1 site), Starter ₹999/mo (25,000, 3 sites), Growth ₹2,999/mo (100,000, 10 sites, 3 seats, audit bundle), Scale ₹7,999/mo (500,000, unlimited sites, 10 seats, no Skope branding). All plans include all languages. Trials get Growth-level limits for 30 days.
- Referrals: share the link on the Billing page; both sides get bonus free days.
- If a trial lapses or a limit is exceeded, the visitor-facing banner KEEPS WORKING, only dashboard editing pauses.

SECURITY & RESIDENCY (what you can truthfully tell customers): data is stored in Mumbai (ap-south-1). End-user personal data (requester contacts and details) is encrypted with AES-256-GCM under a per-organisation key; deleting the org destroys the key, making the data unrecoverable even in backups. Receipts contain no raw PII: IPs are truncated, user agents are hashed.

WHAT SKOPE DOES NOT DO (don't invent features): no cookie-wall/paywall mode, no per-site custom purposes yet (the three fixed purposes), no DSAR identity-document verification, no on-premise hosting, no Android/iOS SDKs. If asked for one of these, say it isn't available today rather than improvising.`;
